### ISSUE TITLE
Would you mind creating a branch that uses mason.nvim instead of lsp-installer?

### ISSUE THREAD

**Issue by voyeg3r** [Blovio/NeoVim_Essentials#3]
[mason.nvim](https://github.com/williamboman/mason.nvim) I think is from the same creator of lsp-installer. 

nvim-lsp-installer will no longer be actively maintained, meaning I won't be doing things like porting new mason.nvim packages to nvim-lsp-installer, monitoring lspconfig for changes that require updates, or put much effort into user support or bug issues (the recommendation for the latter will be to migrate to mason.nvim).

**Comment by json-bateman** [comment]
Thanks, yea i've been meaning to update this. Instead of making a branch I just pushed directly to master. I think this is good to have for the future anyway, lsp-installer is deprecated now.
