### ISSUE TITLE
ftplugin for help files

### ISSUE THREAD

**Issue by voyeg3r** [Blovio/NeoVim_Essentials#6]
```lua
-- $HOME/.config/nvim/after/ftplugin/help.lua
-- Last Change: Fri, Aug 19 2022 - 15:52

-- close help files just typing "q"
vim.keymap.set("n", "q", "<cmd>close!<cr>", {noremap = true, silent = true , desc = "Close help files with q"} )
```

**Comment by voyeg3r** [comment]
Another cool idea is to put a header on each file so it is easier to know which file are you editing. 

These ftplugin files are trigger automatically as if we have created autocommands with "FileType"

**Comment by json-bateman** [comment]
These are good ideas but it's more custom behavior for your own setup, this is supposed to be a more general setup for people to use.
